controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    left_wheel_names: ["LF_wheel_to_lower_suspension", "LM_wheel_to_lower_suspension", "LR_wheel_to_lower_suspension"]
    right_wheel_names: ["RF_wheel_to_lower_suspension", "RM_wheel_to_lower_suspension", "RR_wheel_to_lower_suspension"]
    # left_wheel_names: ["RF_wheel_to_lower_suspension"]
    # right_wheel_names: ["LF_wheel_to_lower_suspension"]

    left_wheel_radius_multiplier: -1.0
    right_wheel_radius_multiplier: 1.0

    open_loop: true
    use_stamped_vel: false
    wheel_separation: 0.35
    wheel_radius: 0.05
    publish_rate: 50.0

